import web3 from './web3';

const address = "0x09D66A7c280FE05b30124be91154c68c4ef449E8";
const abi = [
  {
    constant: false,
    inputs: [{ name: "proposal", type: "uint256" }],
    name: "vote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "name", type: "bytes32" },
      { name: "voteCount", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "stopElection",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "manager",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "winningProposal",
    outputs: [{ name: "winningProposal_", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getProposals",
    outputs: [{ name: "allProposals", type: "bytes32[]" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "voter", type: "address" }],
    name: "giveRightToVote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "voters",
    outputs: [
      { name: "weight", type: "uint256" },
      { name: "voted", type: "bool" },
      { name: "vote", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "winnerName",
    outputs: [{ name: "winnerName_", type: "bytes32" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "proposalNames", type: "bytes32[]" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];
export default new web3.eth.Contract(abi, address);